version: '3.7'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  service2:
    build:
      context: ./service2
    ports:
      - "8082:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  service3:
    build:
      context: ./service3
    ports:
      - "8083:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  app-network:
    driver: bridge
